# Generated by Django 4.1.2 on 2022-10-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_file_and_chunk'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='filechunk',
            constraint=models.UniqueConstraint(fields=('file', 'index'), name='file_chunk_index_unique'),
        ),
    ]
