# Generated by Django 4.1.2 on 2022-10-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_chunk_del_useles_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
